package nosurf

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"io"
)

const (
	rawTokenLength = 32
)

var (
	tokenLength = base64.StdEncoding.EncodedLen(rawTokenLength)
)

// A token is generated by reading rawTokenLength bytes
// from crypto/rand and encoding that as base64

func generateToken() string {
	bytes := make([]byte, rawTokenLength)
	_, _ = io.ReadFull(rand.Reader, bytes)
	// I'm not sure how to handle an error here.
	// It shouldn't EVER really happen,
	// As we check for the availablity of crypto/random
	// in the init() function.

	return base64.StdEncoding.EncodeToString(bytes)
}

func init() {
	// Check that cryptographically secure PRNG is available
	// In case it's not, panic.
	buf := make([]byte, 1)
	_, err := io.ReadFull(rand.Reader, buf)

	if err != nil {
		panic(fmt.Sprintf("crypto/rand is unavailable: Read() failed with %#v", err))
	}
}
